const crypto = require('crypto');
const { redisSetNX } = require('./coupons');

const sign = (value, secret) =>
  crypto.createHmac('sha256', secret).update(value).digest('hex');

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ verified: false });
  }

  try {
    const { token } = req.body || {};
    const secret = process.env.RAZORPAY_KEY_SECRET;

    if (!token || !secret) {
      return res.status(400).json({ verified: false });
    }

    const parts = String(token).split('.');
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      return res.status(400).json({ verified: false });
    }

    // Verify that the token was generated by our backend.
    const expected = sign(parts[0], secret);
    const supplied = parts[1];

    if (
      expected.length !== supplied.length ||
      !crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(supplied))
    ) {
      return res.status(400).json({ verified: false });
    }

    let data;
    try {
      data = JSON.parse(Buffer.from(parts[0], 'base64url').toString('utf8'));
    } catch {
      return res.status(400).json({ verified: false });
    }

    // Token lifetime: 10 minutes.
    if (!data.exp || Date.now() > Number(data.exp)) {
      return res.status(400).json({ verified: false });
    }

    if (
      !data.payment_id ||
      !data.order_id ||
      data.currency !== 'INR' ||
      !Number.isFinite(Number(data.amount)) ||
      Number(data.amount) <= 0
    ) {
      return res.status(400).json({ verified: false });
    }

    // Server-side one-time claim for Meta Purchase attribution.
    // Unlike localStorage, this works across different browsers/devices.
    const purchaseClaimKey = 'meta:purchase:claimed:' + String(data.payment_id);
    const shouldTrackPurchase = await redisSetNX(
      purchaseClaimKey,
      JSON.stringify({
        payment_id: data.payment_id,
        order_id: data.order_id,
        claimedAt: Date.now()
      }),
      31536000
    );

    return res.status(200).json({
      verified: true,
      amount: Number(data.amount),
      currency: data.currency,
      payment_id: data.payment_id,
      should_track_purchase: Boolean(shouldTrackPurchase)
    });
  } catch (error) {
    console.error('Token verification error:', error);
    return res.status(400).json({ verified: false });
  }
};
