const redisUrl=process.env.KV_REST_API_URL;const redisToken=process.env.KV_REST_API_TOKEN;const adminSecret=process.env.ADMIN_SECRET;
async function redis(command,...args){if(!redisUrl||!redisToken)throw new Error("Redis analytics is not configured.");const path=[command,...args.map(v=>encodeURIComponent(String(v)))].join("/");const r=await fetch(redisUrl.replace(/\/$/,"")+"/"+path,{headers:{Authorization:"Bearer "+redisToken}});if(!r.ok)throw new Error("Redis request failed.");return r.json()}
function authorized(req){return !!adminSecret&&String(req.headers.authorization||"")==="Bearer "+adminSecret}
function startOfUtcDay(ts){const d=new Date(ts);return Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())}
function isoDate(ts){return new Date(ts).toISOString().slice(0,10)}
function parseRange(req){const q=req.query||{},now=Date.now(),range=String(q.range||"today").toLowerCase();if(range==="custom"){const start=Date.parse(String(q.start||"")),end=Date.parse(String(q.end||""));if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new Error("Invalid custom date range.");return {start,end,range}}
 const today=startOfUtcDay(now);switch(range){case"yesterday":return{start:today-86400000,end:today,range};case"7d":case"last_7_days":return{start:today-6*86400000,end:today+86400000,range:"7d"};case"30d":case"last_30_days":return{start:today-29*86400000,end:today+86400000,range:"30d"};case"this_week":{const day=new Date(today).getUTCDay();return{start:today-day*86400000,end:today+86400000,range}}case"last_week":{const day=new Date(today).getUTCDay(),w=today-day*86400000;return{start:w-7*86400000,end:w,range}}case"this_month":{const d=new Date(today);return{start:Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1),end:today+86400000,range}}case"last_month":{const d=new Date(today);return{start:Date.UTC(d.getUTCFullYear(),d.getUTCMonth()-1,1),end:Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1),range}}default:return{start:today,end:today+86400000,range:"today"}}}
function addCounts(target,hash){const raw=hash?.result;if(Array.isArray(raw)){for(let i=0;i+1<raw.length;i+=2){const n=Number(raw[i+1]||0);if(Number.isFinite(n))target[String(raw[i])]=(target[String(raw[i])]||0)+n}}else if(raw&&typeof raw==="object")for(const[k,v]of Object.entries(raw)){const n=Number(v||0);if(Number.isFinite(n))target[k]=(target[k]||0)+n}}
async function daily(start,end){const first=startOfUtcDay(start),last=startOfUtcDay(end-1),days=[];for(let t=first;t<=last;t+=86400000)days.push(isoDate(t));const rows=await Promise.all(days.map(async day=>{const [counter,revenue,visitors,newVisitors,sessions,pages,sources,devices,buyCtas,scroll]=await Promise.all([redis("hgetall","analytics:counter:"+day),redis("hget","analytics:revenue:"+day,"value"),redis("smembers","analytics:visitors:"+day),redis("smembers","analytics:new_visitors:"+day),redis("smembers","analytics:sessions:"+day),redis("hgetall","analytics:pages:"+day),redis("hgetall","analytics:sources:"+day),redis("hgetall","analytics:devices:"+day),redis("hgetall","analytics:buy_ctas:"+day),redis("hgetall","analytics:scroll:"+day)]);return{day,counter,revenue:Number(revenue.result||0),visitors,newVisitors,sessions,pages,sources,devices,buyCtas,scroll}}));
 const pages={},sources={},devices={},buyCtas={},scroll={},events={},visitorIds=new Set(),newVisitorIds=new Set(),sessionIds=new Set();let revenue=0;for(const row of rows){addCounts(events,row.counter);addCounts(pages,row.pages);addCounts(sources,row.sources);addCounts(devices,row.devices);addCounts(buyCtas,row.buyCtas);addCounts(scroll,row.scroll);revenue+=Number.isFinite(row.revenue)?row.revenue:0;const vs=Array.isArray(row.visitors?.result)?row.visitors.result:[],ss=Array.isArray(row.sessions?.result)?row.sessions.result:[];vs.forEach(x=>visitorIds.add(String(x)));const nvs=Array.isArray(row.newVisitors?.result)?row.newVisitors.result:[];nvs.forEach(x=>newVisitorIds.add(String(x)));ss.forEach(x=>sessionIds.add(String(x)))}return{pages,sources,devices,buyCtas,scroll,events,revenue,visitors:newVisitorIds.size,return_visitors:visitorIds.size,sessions:sessionIds.size}}
module.exports=async(req,res)=>{if(!authorized(req))return res.status(401).json({message:"Unauthorized"});if(req.method!=="GET")return res.status(405).json({message:"Method not allowed"});try{const now=Date.now(),{start,end,range}=parseRange(req);await redis("zremrangebyscore","analytics:active","-inf",now-90000);const [d,active,visitorsTotal,eventsRaw]=await Promise.all([daily(start,end),redis("zcard","analytics:active"),redis("scard","analytics:visitors"),redis("lrange","analytics:events","0","9999")]);
 let purchases=0,eventRevenue=0;const rows=Array.isArray(eventsRaw.result)?eventsRaw.result:[];for(const raw of rows){let e;try{e=typeof raw==="string"?JSON.parse(raw):raw}catch(_){continue}const ts=Number(e?.ts);if(!e||ts<start||ts>=end)continue;if(e.event==="purchase"){purchases++;const a=Number(e.data?.amount);if(Number.isFinite(a))eventRevenue+=a}}
 const pageViews=Object.values(d.pages).reduce((a,b)=>a+b,0),buyClicks=Object.values(d.buyCtas).reduce((a,b)=>a+b,0),checkoutViews=Number(d.events.checkout_view||0),paymentFailures=Number(d.events.payment_failed_unique||0),revenue=Number(Math.max(d.revenue,eventRevenue).toFixed(2));
 const paymentAttempts=purchases+paymentFailures;
 const funnel={visitors:d.visitors,sessions:d.sessions,page_views:pageViews,buy_clicks:buyClicks,checkout_views:checkoutViews,payment_attempts:paymentAttempts,payment_failures:paymentFailures,purchases,revenue};
 return res.status(200).json({generated_at:now,range,start,end,active_users:Number(active.result||0),unique_visitors_total:Number(visitorsTotal.result||0),funnel,conversion_rate:buyClicks?Number((purchases/buyClicks*100).toFixed(2)):0,visitor_to_purchase_rate:d.visitors?Number((purchases/d.visitors*100).toFixed(2)):0,payment_success_rate:paymentAttempts?Number((purchases/paymentAttempts*100).toFixed(2)):0,events:d.events,top_pages:Object.entries(d.pages).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([page,count])=>({page,count})),traffic_sources:Object.entries(d.sources).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([source,count])=>({source,count})),devices:Object.entries(d.devices).sort((a,b)=>b[1]-a[1]).map(([device,count])=>({device,count})),buy_ctas:Object.entries(d.buyCtas).sort((a,b)=>b[1]-a[1]).map(([cta,count])=>({cta,count})),scroll_depth:d.scroll});
 }catch(error){console.error("Analytics stats error:",error);return res.status(400).json({message:error.message||"Unable to load analytics."})}};
